rm ../samples/test/woman/andrea/andrea-woman-rbf3-predict
rm ../samples/test/woman/andrea/andrea-woman-rbf3-predict-results 
rm ../samples/test/woman/andrea/andrea-woman_man-rbf3-predict
rm ../samples/test/woman/andrea/andrea-woman_man-rbf3-predict-results 
rm ../samples/test/woman/mama/mama-woman-rbf3-predict
rm ../samples/test/woman/mama/mama-woman-rbf3-predict-results 
rm ../samples/test/woman/mama/mama-woman_man-rbf3-predict
rm ../samples/test/woman/mama/mama-woman_man-rbf3-predict-results 
rm ../samples/test/woman/marce/marce-woman-rbf3-predict
rm ../samples/test/woman/marce/marce-woman-rbf3-predict-results 
rm ../samples/test/woman/marce/marce-woman_man-rbf3-predict
rm ../samples/test/woman/marce/marce-woman_man-rbf3-predict-results 
rm ../samples/test/woman/noe/noe-woman-rbf3-predict
rm ../samples/test/woman/noe/noe-woman-rbf3-predict-results 
rm ../samples/test/woman/noe/noe-woman_man-rbf3-predict
rm ../samples/test/woman/noe/noe-woman_man-rbf3-predict-results 
rm ../samples/test/woman/tamara/tamara-woman-rbf3-predict
rm ../samples/test/woman/tamara/tamara-woman-rbf3-predict-results 
rm ../samples/test/woman/tamara/tamara-woman_man-rbf3-predict
rm ../samples/test/woman/tamara/tamara-woman_man-rbf3-predict-results 
rm ../samples/test/man/gust/gust-man-rbf3-predict
rm ../samples/test/man/gust/gust-man-rbf3-predict-results 
rm ../samples/test/man/gust/gust-woman_man-rbf3-predict
rm ../samples/test/man/gust/gust-woman_man-rbf3-predict-results 
rm ../samples/test/man/ivan/ivan-man-rbf3-predict
rm ../samples/test/man/ivan/ivan-man-rbf3-predict-results 
rm ../samples/test/man/ivan/ivan-woman_man-rbf3-predict
rm ../samples/test/man/ivan/ivan-woman_man-rbf3-predict-results 
rm ../samples/test/man/mati/mati-man-rbf3-predict
rm ../samples/test/man/mati/mati-man-rbf3-predict-results 
rm ../samples/test/man/mati/mati-woman_man-rbf3-predict
rm ../samples/test/man/mati/mati-woman_man-rbf3-predict-results 
rm ../samples/test/man/papa/papa-man-rbf3-predict
rm ../samples/test/man/papa/papa-man-rbf3-predict-results 
rm ../samples/test/man/papa/papa-woman_man-rbf3-predict
rm ../samples/test/man/papa/papa-woman_man-rbf3-predict-results 
rm ../samples/test/man/vito/vito-man-rbf3-predict
rm ../samples/test/man/vito/vito-man-rbf3-predict-results 
rm ../samples/test/man/vito/vito-woman_man-rbf3-predict
rm ../samples/test/man/vito/vito-woman_man-rbf3-predict-results 